### ISSUE TITLE
ImportError: MemoryLoadLibrary failed loading win32ui.pyd

### ISSUE THREAD

**Issue by KennethVanMele** [pmsosa/duckhunt#2]
When using the 'advanced' install I get the following log.txt content when running dist/duckhunt.exe:

 Traceback (most recent call last):
  File "duckhunt.pyw", line 11, in <module>
  File "zipextimporter.pyc", line 98, in load_module
ImportError: MemoryLoadLibrary failed loading win32ui.pyd

A quick google suggests this might be a py2exe problem. I have a little python knowledge but I'm new to py2exe so I can't confirm this nor know a fix. Feel free to close if I did something wrong.

**Comment by pmsosa** [comment]
Hmm, I can't quite replicate this error, but I have read of people solving this issue by going to the file: [setup.py](https://github.com/pmsosa/duckhunt/blob/master/setup.py) and changing the `'bundle_files': 1` to `'bundle_files': 3` on line 11.

Let me know if that worked.

**Comment by KennethVanMele** [comment]
It works now thanks. Just one thing: duckhunt.pyw line 17 should be: `duckhunt = imp.load_source('../duckhunt', '../duckhunt.conf')`
